fixed Windows OS file system path issue
dcbarrett/vscode-coffeescript-preview pull request #4
Opened 2017-01-15 23:11 UTC by stephenc222

https://github.com/dcbarrett/vscode-coffeescript-preview/issues/3

This PR fixes the Windows OS file path generation issue above.

2017-01-17 21:56 UTC, dcbarrett commented
@stephenc222 Thanks for submitting a PR for the issue. The change looks good to me, but a test should be added to cover the scenario. The generatePreviewUri function is tested indirectly in the updateContent function test [here](https://github.com/dcbarrett/vscode-coffeescript-preview/blob/master/test/coffeescript-preview.test.ts#L51). We may be able to inspect the URI object to ensure to appropriate separator is being used. Do you want to add the test?

2017-01-17 21:57 UTC, dcbarrett requested changes
Let's add a test for the scenario

2017-01-17 22:08 UTC, stephenc222 commented
Definitely! I'll add the test and update the PR. Thanks for the feedback!

2017-01-19 16:39 UTC, dcbarrett approved these changes

2017-01-19 16:39 UTC, dcbarrett commented on test/coffeescript-preview.test.ts
> +        assert.equal(stub.getCall(0).args[0].toString().includes(separator), true);
This looks like a great start. I'm thinking we should divide the test into two and test both scenarios (Windows and non-Windows). I'll go ahead and merge as is and see about adding it in.

2017-01-19 16:41 UTC, dcbarrett commented
Thanks for adding the test. I'll see about getting this deployed soon. I just welcomed a new addition to the family so it may be a few days, but I'll try to get to it asap.

2017-01-19 16:43 UTC, merged

2017-01-19 21:05 UTC, stephenc222 commented
Congratulations! Happy to help make an awesome vsc extension a tiny bit better!